/* automatically generated by rust-bindgen 0.72.1 */

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]

pub type VmbInt8_t = ::std::os::raw::c_schar;
pub type VmbUint8_t = ::std::os::raw::c_uchar;
pub type VmbInt16_t = ::std::os::raw::c_short;
pub type VmbUint16_t = ::std::os::raw::c_ushort;
pub type VmbInt32_t = ::std::os::raw::c_int;
pub type VmbUint32_t = ::std::os::raw::c_uint;
pub type VmbInt64_t = ::std::os::raw::c_longlong;
pub type VmbUint64_t = ::std::os::raw::c_ulonglong;
pub type VmbHandle_t = *mut ::std::os::raw::c_void;
pub type VmbBool_t = ::std::os::raw::c_char;
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum VmbBoolVal {
    VmbBoolTrue = 1,
    VmbBoolFalse = 0,
}
pub type VmbUchar_t = ::std::os::raw::c_uchar;
pub type VmbFilePathChar_t = ::std::os::raw::c_char;
#[repr(i32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum VmbErrorType {
    VmbErrorSuccess = 0,
    VmbErrorInternalFault = -1,
    VmbErrorApiNotStarted = -2,
    VmbErrorNotFound = -3,
    VmbErrorBadHandle = -4,
    VmbErrorDeviceNotOpen = -5,
    VmbErrorInvalidAccess = -6,
    VmbErrorBadParameter = -7,
    VmbErrorStructSize = -8,
    VmbErrorMoreData = -9,
    VmbErrorWrongType = -10,
    VmbErrorInvalidValue = -11,
    VmbErrorTimeout = -12,
    VmbErrorOther = -13,
    VmbErrorResources = -14,
    VmbErrorInvalidCall = -15,
    VmbErrorNoTL = -16,
    VmbErrorNotImplemented = -17,
    VmbErrorNotSupported = -18,
    VmbErrorIncomplete = -19,
    VmbErrorIO = -20,
    VmbErrorValidValueSetNotPresent = -21,
    VmbErrorGenTLUnspecified = -22,
    VmbErrorUnspecified = -23,
    VmbErrorBusy = -24,
    VmbErrorNoData = -25,
    VmbErrorParsingChunkData = -26,
    VmbErrorInUse = -27,
    VmbErrorUnknown = -28,
    VmbErrorXml = -29,
    VmbErrorNotAvailable = -30,
    VmbErrorNotInitialized = -31,
    VmbErrorInvalidAddress = -32,
    VmbErrorAlready = -33,
    VmbErrorNoChunkData = -34,
    VmbErrorUserCallbackException = -35,
    VmbErrorFeaturesUnavailable = -36,
    VmbErrorTLNotFound = -37,
    VmbErrorAmbiguous = -39,
    VmbErrorRetriesExceeded = -40,
    VmbErrorInsufficientBufferCount = -41,
    VmbErrorCustom = 1,
}
pub type VmbError_t = VmbInt32_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VmbVersionInfo {
    pub major: VmbUint32_t,
    pub minor: VmbUint32_t,
    pub patch: VmbUint32_t,
}
pub type VmbVersionInfo_t = VmbVersionInfo;
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum VmbPixelType {
    VmbPixelMono = 16777216,
    VmbPixelColor = 33554432,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum VmbPixelOccupyType {
    VmbPixelOccupy8Bit = 524288,
    VmbPixelOccupy10Bit = 655360,
    VmbPixelOccupy12Bit = 786432,
    VmbPixelOccupy14Bit = 917504,
    VmbPixelOccupy16Bit = 1048576,
    VmbPixelOccupy24Bit = 1572864,
    VmbPixelOccupy32Bit = 2097152,
    VmbPixelOccupy48Bit = 3145728,
    VmbPixelOccupy64Bit = 4194304,
}
impl VmbPixelFormatType {
    pub const VmbPixelFormatRgba8: VmbPixelFormatType = VmbPixelFormatType::VmbPixelFormatArgb8;
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum VmbPixelFormatType {
    VmbPixelFormatMono8 = 17301505,
    VmbPixelFormatMono10 = 17825795,
    VmbPixelFormatMono10p = 17432646,
    VmbPixelFormatMono12 = 17825797,
    VmbPixelFormatMono12Packed = 17563654,
    VmbPixelFormatMono12p = 17563719,
    VmbPixelFormatMono14 = 17825829,
    VmbPixelFormatMono16 = 17825799,
    VmbPixelFormatBayerGR8 = 17301512,
    VmbPixelFormatBayerRG8 = 17301513,
    VmbPixelFormatBayerGB8 = 17301514,
    VmbPixelFormatBayerBG8 = 17301515,
    VmbPixelFormatBayerGR10 = 17825804,
    VmbPixelFormatBayerRG10 = 17825805,
    VmbPixelFormatBayerGB10 = 17825806,
    VmbPixelFormatBayerBG10 = 17825807,
    VmbPixelFormatBayerGR12 = 17825808,
    VmbPixelFormatBayerRG12 = 17825809,
    VmbPixelFormatBayerGB12 = 17825810,
    VmbPixelFormatBayerBG12 = 17825811,
    VmbPixelFormatBayerGR12Packed = 17563690,
    VmbPixelFormatBayerRG12Packed = 17563691,
    VmbPixelFormatBayerGB12Packed = 17563692,
    VmbPixelFormatBayerBG12Packed = 17563693,
    VmbPixelFormatBayerGR10p = 17432662,
    VmbPixelFormatBayerRG10p = 17432664,
    VmbPixelFormatBayerGB10p = 17432660,
    VmbPixelFormatBayerBG10p = 17432658,
    VmbPixelFormatBayerGR12p = 17563735,
    VmbPixelFormatBayerRG12p = 17563737,
    VmbPixelFormatBayerGB12p = 17563733,
    VmbPixelFormatBayerBG12p = 17563731,
    VmbPixelFormatBayerGR16 = 17825838,
    VmbPixelFormatBayerRG16 = 17825839,
    VmbPixelFormatBayerGB16 = 17825840,
    VmbPixelFormatBayerBG16 = 17825841,
    VmbPixelFormatRgb8 = 35127316,
    VmbPixelFormatBgr8 = 35127317,
    VmbPixelFormatRgb10 = 36700184,
    VmbPixelFormatBgr10 = 36700185,
    VmbPixelFormatRgb12 = 36700186,
    VmbPixelFormatBgr12 = 36700187,
    VmbPixelFormatRgb14 = 36700254,
    VmbPixelFormatBgr14 = 36700234,
    VmbPixelFormatRgb16 = 36700211,
    VmbPixelFormatBgr16 = 36700235,
    VmbPixelFormatArgb8 = 35651606,
    VmbPixelFormatBgra8 = 35651607,
    VmbPixelFormatRgba10 = 37748831,
    VmbPixelFormatBgra10 = 37748812,
    VmbPixelFormatRgba12 = 37748833,
    VmbPixelFormatBgra12 = 37748814,
    VmbPixelFormatRgba14 = 37748835,
    VmbPixelFormatBgra14 = 37748816,
    VmbPixelFormatRgba16 = 37748836,
    VmbPixelFormatBgra16 = 37748817,
    VmbPixelFormatYuv411 = 34340894,
    VmbPixelFormatYuv422 = 34603039,
    VmbPixelFormatYuv444 = 35127328,
    VmbPixelFormatYuv422_8 = 34603058,
    VmbPixelFormatYCbCr8_CbYCr = 35127354,
    VmbPixelFormatYCbCr422_8 = 34603067,
    VmbPixelFormatYCbCr411_8_CbYYCrYY = 34340924,
    VmbPixelFormatYCbCr601_8_CbYCr = 35127357,
    VmbPixelFormatYCbCr601_422_8 = 34603070,
    VmbPixelFormatYCbCr601_411_8_CbYYCrYY = 34340927,
    VmbPixelFormatYCbCr709_8_CbYCr = 35127360,
    VmbPixelFormatYCbCr709_422_8 = 34603073,
    VmbPixelFormatYCbCr709_411_8_CbYYCrYY = 34340930,
    VmbPixelFormatYCbCr422_8_CbYCrY = 34603075,
    VmbPixelFormatYCbCr601_422_8_CbYCrY = 34603076,
    VmbPixelFormatYCbCr709_422_8_CbYCrY = 34603077,
    VmbPixelFormatYCbCr411_8 = 34340954,
    VmbPixelFormatYCbCr8 = 35127387,
    VmbPixelFormatLast = 35127388,
}
pub type VmbPixelFormat_t = VmbUint32_t;
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum VmbTransportLayerType {
    VmbTransportLayerTypeUnknown = 0,
    VmbTransportLayerTypeGEV = 1,
    VmbTransportLayerTypeCL = 2,
    VmbTransportLayerTypeIIDC = 3,
    VmbTransportLayerTypeUVC = 4,
    VmbTransportLayerTypeCXP = 5,
    VmbTransportLayerTypeCLHS = 6,
    VmbTransportLayerTypeU3V = 7,
    VmbTransportLayerTypeEthernet = 8,
    VmbTransportLayerTypePCI = 9,
    VmbTransportLayerTypeCustom = 10,
    VmbTransportLayerTypeMixed = 11,
}
pub type VmbTransportLayerType_t = VmbUint32_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VmbTransportLayerInfo {
    pub transportLayerIdString: *const ::std::os::raw::c_char,
    pub transportLayerName: *const ::std::os::raw::c_char,
    pub transportLayerModelName: *const ::std::os::raw::c_char,
    pub transportLayerVendor: *const ::std::os::raw::c_char,
    pub transportLayerVersion: *const ::std::os::raw::c_char,
    pub transportLayerPath: *const ::std::os::raw::c_char,
    pub transportLayerHandle: VmbHandle_t,
    pub transportLayerType: VmbTransportLayerType_t,
}
pub type VmbTransportLayerInfo_t = VmbTransportLayerInfo;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VmbInterfaceInfo {
    pub interfaceIdString: *const ::std::os::raw::c_char,
    pub interfaceName: *const ::std::os::raw::c_char,
    pub interfaceHandle: VmbHandle_t,
    pub transportLayerHandle: VmbHandle_t,
    pub interfaceType: VmbTransportLayerType_t,
}
pub type VmbInterfaceInfo_t = VmbInterfaceInfo;
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum VmbAccessModeType {
    VmbAccessModeNone = 0,
    VmbAccessModeFull = 1,
    VmbAccessModeRead = 2,
    VmbAccessModeUnknown = 4,
    VmbAccessModeExclusive = 8,
}
pub type VmbAccessMode_t = VmbUint32_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VmbCameraInfo {
    pub cameraIdString: *const ::std::os::raw::c_char,
    pub cameraIdExtended: *const ::std::os::raw::c_char,
    pub cameraName: *const ::std::os::raw::c_char,
    pub modelName: *const ::std::os::raw::c_char,
    pub serialString: *const ::std::os::raw::c_char,
    pub transportLayerHandle: VmbHandle_t,
    pub interfaceHandle: VmbHandle_t,
    pub localDeviceHandle: VmbHandle_t,
    pub streamHandles: *const VmbHandle_t,
    pub streamCount: VmbUint32_t,
    pub permittedAccess: VmbAccessMode_t,
}
pub type VmbCameraInfo_t = VmbCameraInfo;
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum VmbFeatureDataType {
    VmbFeatureDataUnknown = 0,
    VmbFeatureDataInt = 1,
    VmbFeatureDataFloat = 2,
    VmbFeatureDataEnum = 3,
    VmbFeatureDataString = 4,
    VmbFeatureDataBool = 5,
    VmbFeatureDataCommand = 6,
    VmbFeatureDataRaw = 7,
    VmbFeatureDataNone = 8,
}
pub type VmbFeatureData_t = VmbUint32_t;
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum VmbFeatureVisibilityType {
    VmbFeatureVisibilityUnknown = 0,
    VmbFeatureVisibilityBeginner = 1,
    VmbFeatureVisibilityExpert = 2,
    VmbFeatureVisibilityGuru = 3,
    VmbFeatureVisibilityInvisible = 4,
}
pub type VmbFeatureVisibility_t = VmbUint32_t;
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum VmbFeatureFlagsType {
    VmbFeatureFlagsNone = 0,
    VmbFeatureFlagsRead = 1,
    VmbFeatureFlagsWrite = 2,
    VmbFeatureFlagsVolatile = 8,
    VmbFeatureFlagsModifyWrite = 16,
}
pub type VmbFeatureFlags_t = VmbUint32_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VmbFeatureInfo {
    pub name: *const ::std::os::raw::c_char,
    pub category: *const ::std::os::raw::c_char,
    pub displayName: *const ::std::os::raw::c_char,
    pub tooltip: *const ::std::os::raw::c_char,
    pub description: *const ::std::os::raw::c_char,
    pub sfncNamespace: *const ::std::os::raw::c_char,
    pub unit: *const ::std::os::raw::c_char,
    pub representation: *const ::std::os::raw::c_char,
    pub featureDataType: VmbFeatureData_t,
    pub featureFlags: VmbFeatureFlags_t,
    pub pollingTime: VmbUint32_t,
    pub visibility: VmbFeatureVisibility_t,
    pub isStreamable: VmbBool_t,
    pub hasSelectedFeatures: VmbBool_t,
}
pub type VmbFeatureInfo_t = VmbFeatureInfo;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VmbFeatureEnumEntry {
    pub name: *const ::std::os::raw::c_char,
    pub displayName: *const ::std::os::raw::c_char,
    pub tooltip: *const ::std::os::raw::c_char,
    pub description: *const ::std::os::raw::c_char,
    pub intValue: VmbInt64_t,
    pub sfncNamespace: *const ::std::os::raw::c_char,
    pub visibility: VmbFeatureVisibility_t,
}
pub type VmbFeatureEnumEntry_t = VmbFeatureEnumEntry;
#[repr(i32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum VmbFrameStatusType {
    VmbFrameStatusComplete = 0,
    VmbFrameStatusIncomplete = -1,
    VmbFrameStatusTooSmall = -2,
    VmbFrameStatusInvalid = -3,
}
pub type VmbFrameStatus_t = VmbInt32_t;
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum VmbFrameFlagsType {
    VmbFrameFlagsNone = 0,
    VmbFrameFlagsDimension = 1,
    VmbFrameFlagsOffset = 2,
    VmbFrameFlagsFrameID = 4,
    VmbFrameFlagsTimestamp = 8,
    VmbFrameFlagsImageData = 16,
    VmbFrameFlagsPayloadType = 32,
    VmbFrameFlagsChunkDataPresent = 64,
}
pub type VmbFrameFlags_t = VmbUint32_t;
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum VmbPayloadType {
    VmbPayloadTypeUnknown = 0,
    VmbPayloadTypeImage = 1,
    VmbPayloadTypeRaw = 2,
    VmbPayloadTypeFile = 3,
    VmbPayloadTypeJPEG = 5,
    VmbPayloadTypJPEG2000 = 6,
    VmbPayloadTypeH264 = 7,
    VmbPayloadTypeChunkOnly = 8,
    VmbPayloadTypeDeviceSpecific = 9,
    VmbPayloadTypeGenDC = 11,
}
pub type VmbPayloadType_t = VmbUint32_t;
pub type VmbImageDimension_t = VmbUint32_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VmbFrame {
    pub buffer: *mut ::std::os::raw::c_void,
    pub bufferSize: VmbUint32_t,
    pub context: [*mut ::std::os::raw::c_void; 4usize],
    pub receiveStatus: VmbFrameStatus_t,
    pub frameID: VmbUint64_t,
    pub timestamp: VmbUint64_t,
    pub imageData: *mut VmbUint8_t,
    pub receiveFlags: VmbFrameFlags_t,
    pub pixelFormat: VmbPixelFormat_t,
    pub width: VmbImageDimension_t,
    pub height: VmbImageDimension_t,
    pub offsetX: VmbImageDimension_t,
    pub offsetY: VmbImageDimension_t,
    pub payloadType: VmbPayloadType_t,
    pub chunkDataPresent: VmbBool_t,
}
pub type VmbFrame_t = VmbFrame;
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum VmbFeaturePersistType {
    VmbFeaturePersistAll = 0,
    VmbFeaturePersistStreamable = 1,
    VmbFeaturePersistNoLUT = 2,
}
pub type VmbFeaturePersist_t = VmbUint32_t;
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum VmbModulePersistFlagsType {
    VmbModulePersistFlagsNone = 0,
    VmbModulePersistFlagsTransportLayer = 1,
    VmbModulePersistFlagsInterface = 2,
    VmbModulePersistFlagsRemoteDevice = 4,
    VmbModulePersistFlagsLocalDevice = 8,
    VmbModulePersistFlagsStreams = 16,
    VmbModulePersistFlagsAll = 255,
}
pub type VmbModulePersistFlags_t = VmbUint32_t;
impl VmbLogLevel {
    pub const VmbLogLevelAll: VmbLogLevel = VmbLogLevel::VmbLogLevelTrace;
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum VmbLogLevel {
    VmbLogLevelNone = 0,
    VmbLogLevelError = 1,
    VmbLogLevelDebug = 2,
    VmbLogLevelWarn = 3,
    VmbLogLevelTrace = 4,
}
pub type VmbLogLevel_t = VmbUint32_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VmbFeaturePersistSettings {
    pub persistType: VmbFeaturePersist_t,
    pub modulePersistFlags: VmbModulePersistFlags_t,
    pub maxIterations: VmbUint32_t,
    pub loggingLevel: VmbLogLevel_t,
}
pub type VmbFeaturePersistSettings_t = VmbFeaturePersistSettings;
pub type VmbInvalidationCallback = ::std::option::Option<
    unsafe extern "C" fn(
        handle: VmbHandle_t,
        name: *const ::std::os::raw::c_char,
        userContext: *mut ::std::os::raw::c_void,
    ),
>;
pub type VmbFrameCallback = ::std::option::Option<
    unsafe extern "C" fn(
        cameraHandle: VmbHandle_t,
        streamHandle: VmbHandle_t,
        frame: *mut VmbFrame_t,
    ),
>;
pub type VmbChunkAccessCallback = ::std::option::Option<
    unsafe extern "C" fn(
        featureAccessHandle: VmbHandle_t,
        userContext: *mut ::std::os::raw::c_void,
    ) -> VmbError_t,
>;
