//! Raw FFI bindings to Allied Vision Vimba X C API (VmbC).
//!
//! This crate exposes the `extern "C"` declarations and C types needed by the
//! safe `vmb` wrapper crate. The bindings were generated by `bindgen` from the
//! Vimba X SDK headers and are committed to `src/bindings.rs`. They are not
//! regenerated at build time; see the crate README for instructions on
//! refreshing them after an SDK upgrade.
//!
//! # Feature flags
//!
//! * `sdk` (default **off**) — enables linking against `libVmbC` (Linux) or
//!   `VmbC.framework` (macOS). Without this feature the crate compiles to a
//!   stub rlib whose `extern "C"` declarations are never resolved, allowing
//!   `cargo build --workspace` to succeed on machines without the SDK.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::upper_case_acronyms)]
#![allow(clippy::missing_safety_doc)]
// bindgen output contains C-style enum naming conventions (e.g.
// `VmbErrorType::VmbErrorSuccess`) that clippy flags as redundant. Silence
// these crate-wide since we do not control the generated file contents.
#![allow(clippy::enum_variant_names)]
#![allow(clippy::useless_transmute)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::unnecessary_cast)]

mod bindings;

pub use bindings::*;

/// Global Vmb API handle used for system-wide operations like camera
/// discovery (`EventCameraDiscovery`). Mirrors the `gVmbHandle` constant
/// declared in `VmbC.h` as `static const` — bindgen does not emit it
/// because it's defined by a preprocessor macro at a file-scope `const`.
///
/// The C header defines:
///
/// ```c
/// #define VMB_API_HANDLE(typeName) \
///     ((typeName)((((VmbUint64_t)1) << (VmbUint64_t)(sizeof(VmbHandle_t) * 8 - 4)) | ((VmbUint64_t) 1)))
/// static const VmbHandle_t gVmbHandle = VMB_API_HANDLE(VmbHandle_t);
/// ```
///
/// On a 64-bit target `sizeof(VmbHandle_t) == 8`, so the shift amount is
/// `8 * 8 - 4 = 60`, yielding `(1 << 60) | 1 == 0x1000_0000_0000_0001`
/// (top nybble = 1, LSB = 1), which the SDK recognises as the "global
/// system" sentinel. It is not a real allocation and must only be passed
/// to APIs that explicitly accept the global handle.
///
/// On a 32-bit target `sizeof(VmbHandle_t) == 4`, so the shift amount is
/// `4 * 8 - 4 = 28`, yielding `(1 << 28) | 1 == 0x1000_0001`.
///
/// # Safety
///
/// This is a sentinel value, not a pointer to real memory. Dereferencing
/// it is undefined behaviour. Pass it only to VmbC functions that
/// document support for `gVmbHandle` (for example
/// `VmbFeatureInvalidationRegister` / `VmbFeatureInvalidationUnregister`
/// with the `EventCameraDiscovery` feature).
#[cfg(target_pointer_width = "64")]
pub const G_VMB_HANDLE: VmbHandle_t =
    core::ptr::without_provenance_mut(0x1000_0000_0000_0001_usize);

#[cfg(target_pointer_width = "32")]
pub const G_VMB_HANDLE: VmbHandle_t = core::ptr::without_provenance_mut(0x1000_0001_usize);
